2021-01-13T13:26:50.108775700Z Traceback (most recent call last):
2021-01-13T13:26:50.108844800Z   File "/tmp/entrypoint.py", line 82, in <module>
2021-01-13T13:26:50.108873000Z     main()
2021-01-13T13:26:50.108898700Z   File "/tmp/entrypoint.py", line 77, in main
2021-01-13T13:26:50.108924400Z     raise FileNotFoundError("/workspace/" + options.script)
2021-01-13T13:26:50.108950000Z FileNotFoundError: /workspace/analysis/21_eth_tested_characteristics


state: failed
commit: none
docker_image_id: sha256:e4a676ff497b1550742032051cce1ba5502f65b172e86e4d82aadbaa1e056935
job_id: sqemhzpvmxqz5d2d
run_by_user: None
created_at: 2021-01-13T13:26:05Z
started_at: 2021-01-13T13:26:50Z
completed_at: 2021-01-13T13:26:52Z

Job exited with an error code

outputs:
  (no outputs)