2021-01-13T13:25:17.247356900Z Traceback (most recent call last):
2021-01-13T13:25:17.247410800Z   File "/tmp/entrypoint.py", line 82, in <module>
2021-01-13T13:25:17.247439000Z     main()
2021-01-13T13:25:17.247464500Z   File "/tmp/entrypoint.py", line 77, in main
2021-01-13T13:25:17.247558800Z     raise FileNotFoundError("/workspace/" + options.script)
2021-01-13T13:25:17.247586300Z FileNotFoundError: /workspace/analysis/21_eth_tested_characteristics


state: failed
commit: none
docker_image_id: sha256:e4a676ff497b1550742032051cce1ba5502f65b172e86e4d82aadbaa1e056935
job_id: 4tqw6kuuy2qx7iln
run_by_user: None
created_at: 2021-01-13T13:24:39Z
started_at: 2021-01-13T13:25:17Z
completed_at: 2021-01-13T13:25:19Z

Job exited with an error code

outputs:
  (no outputs)